### PR TITLE
Update Derivatives draft

### PR DESCRIPTION
**Pull request by sean-fitzpatrick**
I've made a few changes to your draft.

- use `\begin{aligned}` instead of `\begin{align*}`
- create some text input boxes for student answers
- fix some LaTeX formatting

One check you should do: make sure that you can download PDF via LaTeX. Trying that alerted me to an error (the first change noted above).

Are you still going to put in an exerise involving bisection?

You could try doing `f(x)=x-\cos(x)` on the interval `[0,\pi/2]`, since f(0) is negative, and f(pi/2) is positive.

You could make the exericse something like: "Find an interval of length pi/32 that contains a zero of f(x)".

If you have time: you could also explain how to use SymPy's `nsolve` to solve x-cos(x)=0 numerically. I think the code would be something like:
```
sy.nsolve(x-sy.cos(x), x, sy.pi/4)
```

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
Also, I may have overlooked it, but did you include anything on doing second or third derivatives?

**Comment by raheemmir** [comment]
I added sections for higher order derivatives, and a bisection example/walkthrough. I did change the student input code cells, back to markdown cells (with brief added instructions), as with the code cells, you can't edit them without running again and starting from scratch.

**Comment by sean-fitzpatrick** [comment]
Ok, your update looks good.

A couple of minor LaTeX nits to pick: 
- I noticed one place with cos instead of \cos (I fixed a bunch of these earlier but must have missed one).
- you can extend brackets using \left[ , \right] so you don't have a fraction that's taller than the bracket

Other than that:

For the higher derivatives example, I think you should go straight to using the computer, since we're not assuming students know any derivative rules yet. (You could point out that it makes sense that the derivative of 12x is 12, since y=12x is a line with slope 12, and that the derivative of 12 is 0, since y=12 is a horizontal line with slope 0.)

For bisection I think you could leave the last two steps for them instead of the last one.

**Comment by raheemmir** [comment]
Just updated it:
-Edited the bisection and higher order derivatives examples
-added the \left and \right for those fractions that were taller than the brackets
-found the cos that wasn't \cos

**Pull request merged**
